# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bD5p6X0i68zZ2zajw_xWEWInhRD9xEUe
"""

import streamlit as st
import pandas as pd
import pickle

# Load model (ensure it's trained on CAR data)
with open('CatBoost_Regressor.pkl', 'rb') as f:
    model = pickle.load(f)

# Streamlit UI
st.title("🚗 Car Price Prediction App")
st.write("This AI predicts car market values using CatBoost Regressor")

# --- CAR-SPECIFIC INPUTS --- #
col1, col2 = st.columns(2)

# Column 1
brand = col1.selectbox("Brand", ['Maruti', 'Hyundai', 'Honda', 'Toyota', 'Ford'])
year = col1.slider("Manufacturing Year", 2000, 2025, 2020)
km_driven = col1.number_input("Kilometers Driven", 0, 500000, 50000)

# Column 2
fuel_type = col2.selectbox("Fuel Type", ["Petrol", "Diesel", "CNG", "Electric"])
transmission = col2.selectbox("Transmission", ["Manual", "Automatic"])
owner_type = col2.selectbox("Owner Type", ["First", "Second", "Third", "Fourth+"])

# --- PREDICTION LOGIC --- #
if st.button("Estimate Price", type="primary"):
    # Convert categorical features to model-compatible format
    input_data = pd.DataFrame({
        'brand': [brand],
        'year': [year],
        'km_driven': [km_driven],
        'fuel_type': [fuel_type],
        'transmission': [transmission],
        'owner_type': [owner_type]
    })

    # Add any necessary feature engineering/encoding here
    prediction = model.predict(input_data)[0]

    # Display result
    st.subheader(f"Estimated Price: ₹{prediction:,.2f}")
    st.balloons()